-- Nefalix Klinik CRM (Stella mantığı) — çekirdek tablolar
-- Kullanıcılar, segment kataloğu, kişiler (lead + danışan), notlar, randevular.
-- Erişim: yalnızca service_role (Vercel api/blog.js clinic-* action'ları).

-- ── Kullanıcılar ─────────────────────────────────────────────
create table if not exists public.crm_users (
  id uuid primary key default gen_random_uuid(),
  kod text not null unique,
  ad text not null,
  rol text not null default 'temsilci' check (rol in ('yonetici', 'temsilci')),
  aktif boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.crm_users (id, kod, ad, rol) values
  ('c0000000-0000-4000-8000-000000000001', 'enes', 'Enes Ceylan', 'yonetici'),
  ('c0000000-0000-4000-8000-000000000002', 'abdulkadir', 'Abdülkadir Yaşar', 'temsilci'),
  ('c0000000-0000-4000-8000-000000000003', 'kader', 'Kader Hanım', 'temsilci')
on conflict (kod) do nothing;

-- ── Segment kataloğu (Stella ekranından doğrulanmış liste) ───
-- show_in_dynamic=true olanlar not kaydından sonra gun_offset gün sonra
-- Dinamik Arama listesine düşer (next_call_date hesaplanır).
create table if not exists public.crm_segments (
  code text primary key,
  label text not null,
  show_in_dynamic boolean not null default true,
  gun_offset int not null default 1,
  sira int not null default 100,
  aktif boolean not null default true
);

insert into public.crm_segments (code, label, show_in_dynamic, gun_offset, sira) values
  ('mesajlasiliyor',       'Mesajlaşılıyor',                  true,  1,  10),
  ('orta_vadede',          'Orta Vadede Düşünecek',           true,  7,  20),
  ('otel_satis',           'Otel Satış',                      false, 0,  30),
  ('potansiyel',           'Potansiyel',                      true,  2,  40),
  ('revizyon',             'Revizyon',                        true,  1,  50),
  ('rontgen_foto',         'Röntgen ve Fotoğraf Gönderecek',  true,  1,  60),
  ('satildi',              'Satıldı',                         false, 0,  70),
  ('sicak',                'Sıcak Alacak',                    true,  1,  80),
  ('sureci_biten',         'Süreci Biten',                    false, 0,  90),
  ('takip',                'Takip',                           true,  2, 100),
  ('tedaviye_uygun_degil', 'Tedaviye Uygun Değil',            false, 0, 110),
  ('teklif_verildi',       'Teklif Verildi',                  true,  1, 120),
  ('tekrar_gelen',         'TEKRAR GELEN LEAD',               true,  1, 130),
  ('ulasilamadi',          'Ulaşılamadı-Tekrar Aranacak',     true,  1, 140)
on conflict (code) do nothing;

-- ── Kişiler: lead + danışan tek tablo ────────────────────────
-- stage: 'lead' (henüz atanmamış/ham) → 'danisan' (temsilciye atanmış).
-- next_call_date: Dinamik Arama kuyruğu = next_call_date <= bugün.
create table if not exists public.crm_contacts (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null default '51738ea8-c12e-40ce-a0e2-42869496d76b',
  file_no bigint generated by default as identity (start with 11150),
  stage text not null default 'lead' check (stage in ('lead', 'danisan')),
  status text not null default 'aktif' check (status in ('aktif', 'arsiv')),
  ad text not null,
  telefon text,
  ulke text default '',
  kaynak text default '',
  kampanya text default '',
  assigned_to uuid references public.crm_users(id),
  segment_code text references public.crm_segments(code),
  next_call_date date,
  created_by uuid references public.crm_users(id),
  updated_by uuid references public.crm_users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_contacts_dynamic_idx
  on public.crm_contacts (next_call_date, status) where next_call_date is not null;
create index if not exists crm_contacts_assigned_idx on public.crm_contacts (assigned_to);
create index if not exists crm_contacts_stage_idx on public.crm_contacts (stage);
create index if not exists crm_contacts_telefon_idx on public.crm_contacts (telefon);

-- ── Not geçmişi ──────────────────────────────────────────────
create table if not exists public.crm_contact_notes (
  id uuid primary key default gen_random_uuid(),
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  body text not null,
  segment_code text references public.crm_segments(code),
  note_date date,
  created_by uuid references public.crm_users(id),
  created_at timestamptz not null default now()
);

create index if not exists crm_contact_notes_contact_idx
  on public.crm_contact_notes (contact_id, created_at desc);

-- ── Randevular ───────────────────────────────────────────────
create table if not exists public.crm_appointments (
  id uuid primary key default gen_random_uuid(),
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz,
  hizmet text default '',
  personel text default '',
  oda text default '',
  tip text default '',
  durum text not null default 'beklemede'
    check (durum in ('beklemede', 'geldi', 'tamamlandi', 'iptal', 'gelmedi')),
  not_text text default '',
  created_by uuid references public.crm_users(id),
  updated_by uuid references public.crm_users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_appointments_start_idx on public.crm_appointments (start_at);
create index if not exists crm_appointments_contact_idx on public.crm_appointments (contact_id);

-- ── updated_at trigger ───────────────────────────────────────
create or replace function public.crm_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_crm_contacts_touch on public.crm_contacts;
create trigger trg_crm_contacts_touch
before update on public.crm_contacts
for each row execute function public.crm_touch_updated_at();

drop trigger if exists trg_crm_appointments_touch on public.crm_appointments;
create trigger trg_crm_appointments_touch
before update on public.crm_appointments
for each row execute function public.crm_touch_updated_at();

-- ── Erişim: yalnızca service_role ────────────────────────────
revoke all on table public.crm_users from anon, authenticated;
revoke all on table public.crm_segments from anon, authenticated;
revoke all on table public.crm_contacts from anon, authenticated;
revoke all on table public.crm_contact_notes from anon, authenticated;
revoke all on table public.crm_appointments from anon, authenticated;

grant select, insert, update, delete on table public.crm_users to service_role;
grant select, insert, update, delete on table public.crm_segments to service_role;
grant select, insert, update, delete on table public.crm_contacts to service_role;
grant select, insert, update, delete on table public.crm_contact_notes to service_role;
grant select, insert, update, delete on table public.crm_appointments to service_role;
